const SUSPICIOUS_TLDS = new Set(['.tk','.ml','.ga','.cf','.gq','.xyz','.top','.club','.online','.site','.icu','.buzz','.fun','.uno','.rest']);
const BRAND_KEYWORDS = ['paypal','apple','google','microsoft','amazon','facebook','instagram','netflix','bank','secure','login','signin','account','verify','update','confirm','ebay','chase','wellsfargo','citibank','irs','gov','support','helpdesk'];
function entropy(s){if(!s)return 0;const freq={};for(const c of s)freq[c]=(freq[c]||0)+1;return -Object.values(freq).reduce((acc,n)=>{const p=n/s.length;return acc+p*Math.log2(p);},0);}
function extractFeatures(url){let parsed;try{parsed=new URL(url.includes('://')?url:'http://'+url);}catch{parsed=new URL('http://unknown');}const hostname=parsed.hostname||'',path=parsed.pathname||'',query=parsed.search||'',full=url.toLowerCase(),domain=hostname.replace(/^www\./,'').toLowerCase(),parts=domain.split('.'),tld=parts.length>1?'.'+parts[parts.length-1]:'';return[Math.min(url.length,300)/300,Math.min(hostname.length,100)/100,Math.min(path.length,200)/200,(url.split('-').length-1)/Math.max(url.length,1),(url.split('.').length-1)/Math.max(url.length,1),url.includes('@')?1:0,(url.split('//').length-1)>1?1:0,hostname.replace(/[^0-9]/g,'').length/Math.max(hostname.length,1),(url.match(/[!#$%^&*()=+\[\]{};'\\:"|,<>?]/g)||[]).length/Math.max(url.length,1),SUSPICIOUS_TLDS.has(tld)?1:0,parts.length>4?1:0,/^\d{1,3}(\.\d{1,3}){3}$/.test(hostname)?1:0,Math.min(BRAND_KEYWORDS.filter(k=>full.includes(k)).length,5)/5,(domain.includes('secure')||domain.includes('login')||domain.includes('verify'))?1:0,(url.match(/%[0-9a-fA-F]{2}/g)||[]).length/Math.max(url.length,1),Math.min(entropy(domain),5)/5,query.length>50?1:0,(query.split('=').length-1)>3?1:0,parsed.protocol==='https:'?1:0,(hostname.split('-').length-1)>2?1:0];}
function predictTree(node,f){if(node.leaf)return node.prob;return f[node.feature]<=node.threshold?predictTree(node.left,f):predictTree(node.right,f);}
function buildReasons(f){const r=[];if(f[11])r.push('🔴 IP address used as hostname');if(f[9])r.push('🔴 Suspicious TLD (.tk/.ml/.xyz...)');if(f[5])r.push('🔴 URL contains @ symbol');if(f[12]>0.4)r.push('🔴 Brand name abuse detected');if(f[13])r.push('🟠 Deceptive words in domain');if(f[10])r.push('🟠 Excessive subdomains');if(f[3]>0.1)r.push('🟠 High hyphen density');if(f[18])r.push('🟢 Site uses HTTPS');if(r.length===0)r.push('🟢 No suspicious signals detected');return r.slice(0,5);}
function renderResult(result){const body=document.getElementById('body'),color=result.color,emoji=result.verdict==='PHISHING'?'⛔':result.verdict==='SUSPICIOUS'?'⚠️':'✅';body.innerHTML=`<div class="verdict-card" style="background:${color}22;border:1px solid ${color}55"><div class="verdict-label">Verdict ${emoji}</div><div class="verdict-text" style="color:${color}">${result.verdict}</div></div><div class="confidence-row"><div class="conf-bar"><div class="conf-fill" style="width:${result.confidence}%;background:${color}"></div></div><div class="conf-pct" style="color:${color}">${result.confidence}%</div></div><div class="url-box">${result.url.slice(0,80)}${result.url.length>80?'…':''}</div><div class="signals">${result.reasons.map(r=>`<div class="signal">${r}</div>`).join('')}</div>`;}
async function analyzeURL(url){const model=await(await fetch(chrome.runtime.getURL('model.json'))).json();const f=extractFeatures(url);const avg=model.trees.map(t=>predictTree(t,f)).reduce((a,b)=>a+b,0)/model.trees.length;let verdict,color;if(avg>=0.70){verdict='PHISHING';color='#e53935';}else if(avg>=0.40){verdict='SUSPICIOUS';color='#fb8c00';}else{verdict='SAFE';color='#43a047';}return{url,verdict,color,confidence:Math.round(avg*100),reasons:buildReasons(f)};}
chrome.tabs.query({active:true,currentWindow:true},async(tabs)=>{const body=document.getElementById('body');const tab=tabs[0];if(!tab||!tab.url){body.innerHTML='<div class="loading">No active tab.</div>';return;}body.innerHTML='<div class="loading">Scanning…</div>';try{const result=await analyzeURL(tab.url);renderResult(result);}catch(e){body.innerHTML=`<div class="loading">Could not scan this page.</div>`;}});
